version: '3'
services:

  # customer-server:
  #   build: .
  #   environment:
  #     - PORT=9000
  #   depends_on:
  #     - mongodb-container  


  mongodb-container:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abhiraaj
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"

  rabbitmq-container:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672

volumes:
  mongo-db: